---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: "shallenge-miner"
    scrape_interval: 5s
    static_configs:
      - targets: ["main:8081"]
